/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import core.Entity;
import core.EntityType;
import core.Item;
import core.ItemInstance;
import core.ItemManager;
import core.Player;
import database.Repository;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author robert
 */
public class StatsScreen extends javax.swing.JFrame {

    /**
     * Creates new form StatsScreen
     */
    public StatsScreen() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        getPlayersButton = new javax.swing.JButton();
        getAllItemTypesButton = new javax.swing.JButton();
        totalEntityCountButton = new javax.swing.JButton();
        totalItemInstanceButton = new javax.swing.JButton();
        totalCountForSpecificEntity = new javax.swing.JButton();
        getAllRandomNamesButton = new javax.swing.JButton();
        listAllEntityTypesButton = new javax.swing.JButton();
        getPlayerInventoryButton = new javax.swing.JButton();
        getEntityTypeDropsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        newRandomNameButton = new javax.swing.JButton();
        addNewItemType = new javax.swing.JButton();
        newEntityTypeButton = new javax.swing.JButton();
        deletePlayerInventoryButton = new javax.swing.JButton();
        addDropToEntityType = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getPlayersButton.setText("Get Players");
        getPlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPlayersButtonActionPerformed(evt);
            }
        });

        getAllItemTypesButton.setText("Get Item Types");
        getAllItemTypesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllItemTypesButtonActionPerformed(evt);
            }
        });

        totalEntityCountButton.setText("Get Total Entity Count");
        totalEntityCountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalEntityCountButtonActionPerformed(evt);
            }
        });

        totalItemInstanceButton.setText("Get total Item Instance Count");
        totalItemInstanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalItemInstanceButtonActionPerformed(evt);
            }
        });

        totalCountForSpecificEntity.setText("Get total Count for specific EntityType");
        totalCountForSpecificEntity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCountForSpecificEntityActionPerformed(evt);
            }
        });

        getAllRandomNamesButton.setText("Get all Random Names");
        getAllRandomNamesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAllRandomNamesButtonActionPerformed(evt);
            }
        });

        listAllEntityTypesButton.setText("List all EntityTypes");
        listAllEntityTypesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllEntityTypesButtonActionPerformed(evt);
            }
        });

        getPlayerInventoryButton.setText("Get Player Inventory");
        getPlayerInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPlayerInventoryButtonActionPerformed(evt);
            }
        });

        getEntityTypeDropsButton.setText("Get EntityType drops");
        getEntityTypeDropsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getEntityTypeDropsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(getAllItemTypesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getPlayersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalEntityCountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalItemInstanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalCountForSpecificEntity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getAllRandomNamesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getPlayerInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(getEntityTypeDropsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(listAllEntityTypesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getPlayersButton)
                    .addComponent(getPlayerInventoryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAllItemTypesButton)
                    .addComponent(getEntityTypeDropsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalEntityCountButton)
                    .addComponent(listAllEntityTypesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalItemInstanceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalCountForSpecificEntity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(getAllRandomNamesButton)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General Stats", jPanel1);

        newRandomNameButton.setText("Add new Random Name");
        newRandomNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRandomNameButtonActionPerformed(evt);
            }
        });

        addNewItemType.setText("Add new Item Type");
        addNewItemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewItemTypeActionPerformed(evt);
            }
        });

        newEntityTypeButton.setText("Add new Entity Type");
        newEntityTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEntityTypeButtonActionPerformed(evt);
            }
        });

        deletePlayerInventoryButton.setText("Delete player inventory");
        deletePlayerInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePlayerInventoryButtonActionPerformed(evt);
            }
        });

        addDropToEntityType.setText("Add drop to EntityType");
        addDropToEntityType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDropToEntityTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newRandomNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addComponent(addNewItemType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newEntityTypeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletePlayerInventoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDropToEntityType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newRandomNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewItemType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newEntityTypeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletePlayerInventoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDropToEntityType)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin Options", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getPlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPlayersButtonActionPerformed
        ArrayList<Player> players = Repository.Instance().getAllPlayers();
        String playerString = "";

        for (Player player : players) {
            playerString += player.getUsername() + "\n";
        }

        JOptionPane.showMessageDialog(rootPane, playerString);

    }//GEN-LAST:event_getPlayersButtonActionPerformed

    private void getAllItemTypesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllItemTypesButtonActionPerformed
        ArrayList<Item> items = Repository.Instance().getAllItems();
        String itemString = "";
        for (Item item : items) {
            itemString += item.getName() + "\n";
        }

        JOptionPane.showMessageDialog(rootPane, itemString);

        // TODO add your handling code here:
    }//GEN-LAST:event_getAllItemTypesButtonActionPerformed

    private void totalItemInstanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalItemInstanceButtonActionPerformed
        ArrayList<ItemInstance> itemInstances = Repository.Instance().getAllItemInstances();
        JOptionPane.showMessageDialog(rootPane, itemInstances.size());
    }//GEN-LAST:event_totalItemInstanceButtonActionPerformed

    private void totalEntityCountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalEntityCountButtonActionPerformed
        ArrayList<Entity> entitys = Repository.Instance().getAllEntitys();
        JOptionPane.showMessageDialog(rootPane, entitys.size());
    }//GEN-LAST:event_totalEntityCountButtonActionPerformed

    private void totalCountForSpecificEntityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCountForSpecificEntityActionPerformed
        ArrayList<EntityType> types = Repository.Instance().getAllEntityTypes();
        ArrayList<Object> entityTypes = new ArrayList<>();
        
        for(EntityType type : types){
            entityTypes.add(type.getName());
        }

        String s = (String) JOptionPane.showInputDialog(
                this.rootPane,
                "Select Entity Type",
                "Type Count",
                JOptionPane.PLAIN_MESSAGE,
                null,
                entityTypes.toArray(),
                null);

//If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            
            int count = 0;
            for(Entity entity : Repository.Instance().getAllEntitys()){
                if(entity.getEntityType().getName().equals(s)){
                    count++;
                }
            }
            
            JOptionPane.showMessageDialog(rootPane, "There are " + count + " " + s + "(s)");
        }else{
             JOptionPane.showMessageDialog(
                        null,
                        "An error occured", "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_totalCountForSpecificEntityActionPerformed

    private void newRandomNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRandomNameButtonActionPerformed
        ArrayList<String> names = Repository.Instance().getAllRandomNames();
        String newRandomName = JOptionPane.showInputDialog("Input new Random name");
        if(names.contains(newRandomName) || newRandomName == null){
            JOptionPane.showMessageDialog(null,"name already exits in database or name input is null", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            Repository.Instance().createName(newRandomName);
            JOptionPane.showMessageDialog(rootPane, "New Random name " + newRandomName + " created!");
        }
    }//GEN-LAST:event_newRandomNameButtonActionPerformed

    private void getAllRandomNamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAllRandomNamesButtonActionPerformed
        ArrayList<String> names = Repository.Instance().getAllRandomNames();
        String nameString = "";
        for(String name : names){
            nameString += name + "\n";
        }
        JOptionPane.showMessageDialog(rootPane, nameString);
    }//GEN-LAST:event_getAllRandomNamesButtonActionPerformed

    private void addNewItemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewItemTypeActionPerformed
        String itemName = JOptionPane.showInputDialog("Input new Item Name");
        String itemDescription= JOptionPane.showInputDialog("Input new Item Description");
        
        ArrayList<Item> items = Repository.Instance().getAllItems();
        for(Item item : items){
            if(item.getName().equals(itemName)){
                JOptionPane.showMessageDialog(null,"name already exits in database or name input is null", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        Repository.Instance().createItem(itemName, itemDescription);
        JOptionPane.showMessageDialog(rootPane, "New Item created!");
    }//GEN-LAST:event_addNewItemTypeActionPerformed

    private void newEntityTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEntityTypeButtonActionPerformed
        
        ArrayList<EntityType> types = Repository.Instance().getAllEntityTypes();
        
        String name = JOptionPane.showInputDialog("Input new EntityType name");
        
        if(name == null){
            JOptionPane.showMessageDialog(null,"name is null", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        for(EntityType type : types){
            if(type.getName().equals(name)){
                JOptionPane.showMessageDialog(null,"name already exits in database", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        String description = JOptionPane.showInputDialog("Input EntityType Description");
        
        try{
        int atk = Integer.valueOf(JOptionPane.showInputDialog("Input EntityType attack"));
        int def = Integer.valueOf(JOptionPane.showInputDialog("Input EntityType defense"));
        int hit = Integer.valueOf(JOptionPane.showInputDialog("Input EntityType hit"));
        int health = Integer.valueOf(JOptionPane.showInputDialog("Input EntityType health"));
        
        Repository.Instance().createNewEntityType(name, description,atk , def, hit, health);
        JOptionPane.showMessageDialog(rootPane, "New EntityType created!");
        
        }catch(NumberFormatException e){
             JOptionPane.showMessageDialog(null,"field is not parseable or null", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_newEntityTypeButtonActionPerformed

    private void addDropToEntityTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDropToEntityTypeActionPerformed
        ArrayList<Item> itemTypes = Repository.Instance().getAllItems();
        ArrayList<Object> itemTypeNames = new ArrayList<>();
        
        Item linkingItem = null;
        EntityType linkingType = null;
        
        for(Item item : itemTypes){
            itemTypeNames.add(item.getName());
        }
        
         String s = (String) JOptionPane.showInputDialog(
                this.rootPane,
                "Select Item Type",
                "Type Count",
                JOptionPane.PLAIN_MESSAGE,
                null,
                itemTypeNames.toArray(),
                null);
         
         if((s != null) && (s.length() > 0)) {
            for(Item item : itemTypes){
                if(item.getName().equals(s)){
                    linkingItem = item;
                    break;
                }
            }
         }
            
            
            ArrayList<EntityType> types = Repository.Instance().getAllEntityTypes();
            ArrayList<Object> entityTypeString = new ArrayList<>();
            
            for(EntityType type : types){
                entityTypeString.add(type.getName());
            }
            
             String q = (String) JOptionPane.showInputDialog(
                this.rootPane,
                "Select EntityType",
                "Type Count",
                JOptionPane.PLAIN_MESSAGE,
                null,
                entityTypeString.toArray(),
                null);
           
           if((q != null) && (q.length() > 0)) {
            for(EntityType et : types){
                if(et.getName().equals(q)){
                    linkingType = et;
                    break;
                }
            }
           
            
            try{
                int dropChance = Integer.valueOf(JOptionPane.showInputDialog("Input drop chance"));
                int minCount = Integer.valueOf(JOptionPane.showInputDialog("Min Items dropped"));
                int maxCount = Integer.valueOf(JOptionPane.showInputDialog("Input Max items dropped"));
                
                Repository.Instance().addEntityDropToEntityType(linkingItem, linkingType, dropChance, minCount, maxCount);
                
                JOptionPane.showMessageDialog(rootPane, "Item drop created");
                
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(
                        null,
                        "An error occured", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        }else{
             JOptionPane.showMessageDialog(
                        null,
                        "An error occured", "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addDropToEntityTypeActionPerformed

    private void deletePlayerInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePlayerInventoryButtonActionPerformed
        ArrayList<Player> players = Repository.Instance().getAllPlayers();
        ArrayList<Object> playerNames = new ArrayList<>();
        
        for(Player player : players){
            playerNames.add(player.getUsername());
        }

        String s = (String) JOptionPane.showInputDialog(
                this.rootPane,
                "Select Player",
                "Type Count",
                JOptionPane.PLAIN_MESSAGE,
                null,
                playerNames.toArray(),
                null);

//If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            
            int count = 0;
            for(Player player : players){
                if(player.getUsername().equals(s)){
                    Repository.Instance().executeQuery("delete from player_inventory where player_inventory.player_id="+player.getPlayerId());
                }
            }
            
            JOptionPane.showMessageDialog(rootPane, "Player Inventory deleted!");
        }else{
             JOptionPane.showMessageDialog(
                        null,
                        "An error occured", "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deletePlayerInventoryButtonActionPerformed

    private void listAllEntityTypesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllEntityTypesButtonActionPerformed
            ArrayList<EntityType> types = Repository.Instance().getAllEntityTypes();
            String typeString = "";
            
            for(EntityType type : types){
                typeString += type.getName() + "\n";
            }
            JOptionPane.showMessageDialog(rootPane, typeString);
            
    }//GEN-LAST:event_listAllEntityTypesButtonActionPerformed

    private void getPlayerInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPlayerInventoryButtonActionPerformed
        ArrayList<Player> players = Repository.Instance().getAllPlayers();
        ArrayList<Object> playerNames = new ArrayList<>();
        
        for(Player player : players){
            playerNames.add(player.getUsername());
        }

        String s = (String) JOptionPane.showInputDialog(
                this.rootPane,
                "Select Player",
                "Type Count",
                JOptionPane.PLAIN_MESSAGE,
                null,
                playerNames.toArray(),
                null);
        
        if ((s != null) && (s.length() > 0)) {
            
            int count = 0;
            for(Player player : players){
                if(player.getUsername().equals(s)){
                    String inventoryItems = "";
                    ArrayList<String> invItemsList = Repository.Instance().getPlayerInventory(player);
                    for(String string : invItemsList){
                        inventoryItems+=string + "\n";
                    }
                    JOptionPane.showMessageDialog(rootPane, inventoryItems);
                    return;
                }
            }
            
            
        }else{
             JOptionPane.showMessageDialog(
                        null,
                        "An error occured", "Error",
                        JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_getPlayerInventoryButtonActionPerformed

    private void getEntityTypeDropsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getEntityTypeDropsButtonActionPerformed
            ItemManager.Instance().init();
            ArrayList<EntityType> types = Repository.Instance().getAllEntityTypes();
            ArrayList<Object> entityTypeString = new ArrayList<>();
            
            for(EntityType type : types){
                entityTypeString.add(type.getName());
            }
            
             String q = (String) JOptionPane.showInputDialog(
                this.rootPane,
                "Select EntityType",
                "Type Count",
                JOptionPane.PLAIN_MESSAGE,
                null,
                entityTypeString.toArray(),
                null);
             
            if((q != null) && (q.length() > 0)) {
            for(EntityType et : types){
                if(et.getName().equals(q)){
                    ArrayList<String> items = Repository.Instance().getEntityTypeDrops(et);
                    String itemList = "";
                    for(String string : items){
                        itemList+= string + "\n";
                    }
                    
                    JOptionPane.showMessageDialog(rootPane, itemList);

                }
            }
         }else{
                JOptionPane.showMessageDialog(
                        null,
                        "An error occured", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
             
    }//GEN-LAST:event_getEntityTypeDropsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDropToEntityType;
    private javax.swing.JButton addNewItemType;
    private javax.swing.JButton deletePlayerInventoryButton;
    private javax.swing.JButton getAllItemTypesButton;
    private javax.swing.JButton getAllRandomNamesButton;
    private javax.swing.JButton getEntityTypeDropsButton;
    private javax.swing.JButton getPlayerInventoryButton;
    private javax.swing.JButton getPlayersButton;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listAllEntityTypesButton;
    private javax.swing.JButton newEntityTypeButton;
    private javax.swing.JButton newRandomNameButton;
    private javax.swing.JButton totalCountForSpecificEntity;
    private javax.swing.JButton totalEntityCountButton;
    private javax.swing.JButton totalItemInstanceButton;
    // End of variables declaration//GEN-END:variables
}
